version: "3"
services:
 showdown: 
   build:
    context: ../showdown 
    dockerfile: Dockerfile
   ports:
   - 8081:8081
   container_name: showdown-server
   restart: always 
   volumes:
   - ../showdown/config.js:/pokemon-showdown/config/config.js
   - ../showdown/usergroups.csv:/pokemon-showdown/config/usergroups.csv
   networks:
   - back

 pmariglia_accept_1:
   depends_on:
     - showdown
   build:
     context: ../pmariglia
     dockerfile: Dockerfile
   expose:
     - 8081
   container_name: pmariglia-accept-1
   restart: always
   volumes:
     - ./../pmariglia/envs/accept1:/showdown/.env
     - ./../datasets/collector:/showdown/dataset
     - ./../teams:/showdown/teams/teams
   networks:
     - back

 mcts:
   depends_on:
     - showdown
     - pmariglia_accept_1
   build:
     context: .
     dockerfile: Dockerfile
   expose:
     - 8081
   container_name: mcts
   environment:
     - USER_CHALLENGE=dlinvcaccept1
   restart: always
   networks:
     - back
     # pmariglia_challenge_1:
     #   depends_on:
     #   - pmariglia_accept_1
     #   - showdown
     #   build:
     #    context: pmariglia
     #    dockerfile: Dockerfile
     #   expose:
     #   - 8081
     #   container_name: pmariglia-challenge-1
     #   restart: always
     #   volumes:
     #   - ./pmariglia/envs/challenge1:/showdown/.env
     #   - ./datasets/collector:/showdown/dataset
     #   - ./teams:/showdown/teams/teams
     #   networks:
     #    back:
     #     ipv4_address: 172.25.0.101


networks:
  back:
   driver: bridge
   ipam:
    config:
    - subnet: 172.25.0.0/24
